# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUi.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(783, 593)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 601, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.DepCity = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.DepCity.setObjectName("DepCity")
        self.DepCity.addItem("")
        self.DepCity.addItem("")
        self.horizontalLayout.addWidget(self.DepCity)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.ArrCity = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.ArrCity.setObjectName("ArrCity")
        self.ArrCity.addItem("")
        self.ArrCity.addItem("")
        self.horizontalLayout.addWidget(self.ArrCity)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.ADT = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.ADT.setProperty("value", 4)
        self.ADT.setObjectName("ADT")
        self.horizontalLayout.addWidget(self.ADT)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.Around = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.Around.setProperty("value", 2)
        self.Around.setObjectName("Around")
        self.horizontalLayout.addWidget(self.Around)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.Timeout = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.Timeout.setProperty("value", 5)
        self.Timeout.setObjectName("Timeout")
        self.horizontalLayout.addWidget(self.Timeout)
        self.SearchButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.SearchButton.setObjectName("SearchButton")
        self.horizontalLayout.addWidget(self.SearchButton)
        self.DepTable = QtWidgets.QTableWidget(Dialog)
        self.DepTable.setGeometry(QtCore.QRect(1, 112, 295, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DepTable.sizePolicy().hasHeightForWidth())
        self.DepTable.setSizePolicy(sizePolicy)
        self.DepTable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DepTable.setAutoFillBackground(False)
        self.DepTable.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"font: 8pt \"宋体\";\n"
"color: rgb(182, 182, 182);")
        self.DepTable.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DepTable.setLineWidth(0)
        self.DepTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DepTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DepTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.DepTable.setAutoScroll(False)
        self.DepTable.setAutoScrollMargin(15)
        self.DepTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.DepTable.setTabKeyNavigation(False)
        self.DepTable.setProperty("showDropIndicator", False)
        self.DepTable.setShowGrid(False)
        self.DepTable.setGridStyle(QtCore.Qt.NoPen)
        self.DepTable.setWordWrap(False)
        self.DepTable.setCornerButtonEnabled(False)
        self.DepTable.setObjectName("DepTable")
        self.DepTable.setColumnCount(7)
        self.DepTable.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        item.setBackground(QtGui.QColor(255, 0, 0, 1))
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.DepTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        item.setBackground(QtGui.QColor(0, 0, 0, 10))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.DepTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.DepTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.DepTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(4, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(5, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.DepTable.setItem(5, 6, item)
        self.DepTable.horizontalHeader().setVisible(False)
        self.DepTable.horizontalHeader().setDefaultSectionSize(42)
        self.DepTable.horizontalHeader().setHighlightSections(False)
        self.DepTable.horizontalHeader().setMinimumSectionSize(42)
        self.DepTable.verticalHeader().setVisible(False)
        self.DepTable.verticalHeader().setDefaultSectionSize(42)
        self.DepTable.verticalHeader().setHighlightSections(False)
        self.DepTable.verticalHeader().setMinimumSectionSize(38)
        self.DepCalendar = QtWidgets.QCalendarWidget(Dialog)
        self.DepCalendar.setGeometry(QtCore.QRect(0, 30, 295, 320))
        self.DepCalendar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DepCalendar.setAutoFillBackground(False)
        self.DepCalendar.setStyleSheet("font: 75 12pt \"微软雅黑\";")
        self.DepCalendar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.DepCalendar.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.DepCalendar.setGridVisible(True)
        self.DepCalendar.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.DepCalendar.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.DepCalendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.DepCalendar.setNavigationBarVisible(True)
        self.DepCalendar.setDateEditEnabled(False)
        self.DepCalendar.setObjectName("DepCalendar")
        self.RetCalendar = QtWidgets.QCalendarWidget(Dialog)
        self.RetCalendar.setGeometry(QtCore.QRect(310, 30, 295, 320))
        self.RetCalendar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.RetCalendar.setAutoFillBackground(False)
        self.RetCalendar.setStyleSheet("font: 75 12pt \"微软雅黑\";")
        self.RetCalendar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.RetCalendar.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.RetCalendar.setGridVisible(True)
        self.RetCalendar.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.RetCalendar.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.RetCalendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.RetCalendar.setNavigationBarVisible(True)
        self.RetCalendar.setDateEditEnabled(False)
        self.RetCalendar.setObjectName("RetCalendar")
        self.RetTable = QtWidgets.QTableWidget(Dialog)
        self.RetTable.setGeometry(QtCore.QRect(310, 110, 295, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RetTable.sizePolicy().hasHeightForWidth())
        self.RetTable.setSizePolicy(sizePolicy)
        self.RetTable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.RetTable.setAutoFillBackground(False)
        self.RetTable.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"font: 8pt \"宋体\";\n"
"color: rgb(182, 182, 182);")
        self.RetTable.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.RetTable.setLineWidth(0)
        self.RetTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RetTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RetTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.RetTable.setAutoScroll(False)
        self.RetTable.setAutoScrollMargin(15)
        self.RetTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.RetTable.setTabKeyNavigation(False)
        self.RetTable.setProperty("showDropIndicator", False)
        self.RetTable.setShowGrid(False)
        self.RetTable.setGridStyle(QtCore.Qt.NoPen)
        self.RetTable.setWordWrap(False)
        self.RetTable.setCornerButtonEnabled(False)
        self.RetTable.setObjectName("RetTable")
        self.RetTable.setColumnCount(7)
        self.RetTable.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        item.setBackground(QtGui.QColor(255, 0, 0, 1))
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.RetTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        item.setBackground(QtGui.QColor(0, 0, 0, 10))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.RetTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.RetTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.RetTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(4, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(5, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.RetTable.setItem(5, 6, item)
        self.RetTable.horizontalHeader().setVisible(False)
        self.RetTable.horizontalHeader().setDefaultSectionSize(42)
        self.RetTable.horizontalHeader().setHighlightSections(False)
        self.RetTable.horizontalHeader().setMinimumSectionSize(42)
        self.RetTable.verticalHeader().setVisible(False)
        self.RetTable.verticalHeader().setDefaultSectionSize(42)
        self.RetTable.verticalHeader().setHighlightSections(False)
        self.RetTable.verticalHeader().setMinimumSectionSize(38)
        self.horizontalLayoutWidget.raise_()
        self.DepCalendar.raise_()
        self.DepTable.raise_()
        self.RetCalendar.raise_()
        self.RetTable.raise_()

        self.retranslateUi(Dialog)
        self.DepCalendar.selectionChanged.connect(self.DepTable.resizeColumnsToContents)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "出发地"))
        self.DepCity.setItemText(0, _translate("Dialog", "北京"))
        self.DepCity.setItemText(1, _translate("Dialog", "巴厘岛"))
        self.label_2.setText(_translate("Dialog", "目的地"))
        self.ArrCity.setItemText(0, _translate("Dialog", "巴厘岛"))
        self.ArrCity.setItemText(1, _translate("Dialog", "北京"))
        self.label_3.setText(_translate("Dialog", "人数"))
        self.label_4.setText(_translate("Dialog", "范围"))
        self.label_5.setText(_translate("Dialog", "超时"))
        self.SearchButton.setText(_translate("Dialog", "查询"))
        __sortingEnabled = self.DepTable.isSortingEnabled()
        self.DepTable.setSortingEnabled(False)
        self.DepTable.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.RetTable.isSortingEnabled()
        self.RetTable.setSortingEnabled(False)
        self.RetTable.setSortingEnabled(__sortingEnabled)

