# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIControlProf.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(429, 300)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 401, 141))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 30, 91, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 73, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PID_AutoInc = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.PID_AutoInc.setChecked(True)
        self.PID_AutoInc.setObjectName("PID_AutoInc")
        self.verticalLayout.addWidget(self.PID_AutoInc)
        self.PID_ManuInc = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.PID_ManuInc.setObjectName("PID_ManuInc")
        self.verticalLayout.addWidget(self.PID_ManuInc)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(110, 30, 281, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(9, 17, 121, 80))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.PID_Kp = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        self.PID_Kp.setKeyboardTracking(False)
        self.PID_Kp.setMaximum(65535.0)
        self.PID_Kp.setProperty("value", 4500.0)
        self.PID_Kp.setObjectName("PID_Kp")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.PID_Kp)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.PID_Ki = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        self.PID_Ki.setKeyboardTracking(False)
        self.PID_Ki.setMaximum(65535.0)
        self.PID_Ki.setProperty("value", 6400.0)
        self.PID_Ki.setObjectName("PID_Ki")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.PID_Ki)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.PID_Kd = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        self.PID_Kd.setKeyboardTracking(False)
        self.PID_Kd.setMaximum(65535.0)
        self.PID_Kd.setProperty("value", 2250.0)
        self.PID_Kd.setObjectName("PID_Kd")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.PID_Kd)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(140, 20, 132, 51))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.PID_Inteval = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.PID_Inteval.setKeyboardTracking(False)
        self.PID_Inteval.setDecimals(0)
        self.PID_Inteval.setMaximum(65535.0)
        self.PID_Inteval.setProperty("value", 20.0)
        self.PID_Inteval.setObjectName("PID_Inteval")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.PID_Inteval)
        self.PID_SetPoint = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.PID_SetPoint.setKeyboardTracking(False)
        self.PID_SetPoint.setMaximum(65535.0)
        self.PID_SetPoint.setProperty("value", 2000.0)
        self.PID_SetPoint.setObjectName("PID_SetPoint")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.PID_SetPoint)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 170, 401, 111))
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 160, 80))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.Prescaler = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.Prescaler.setKeyboardTracking(False)
        self.Prescaler.setDecimals(0)
        self.Prescaler.setMaximum(100.0)
        self.Prescaler.setProperty("value", 1.0)
        self.Prescaler.setObjectName("Prescaler")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Prescaler)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.SmoothWindow = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.SmoothWindow.setKeyboardTracking(False)
        self.SmoothWindow.setDecimals(0)
        self.SmoothWindow.setMaximum(65535.0)
        self.SmoothWindow.setProperty("value", 500.0)
        self.SmoothWindow.setObjectName("SmoothWindow")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.SmoothWindow)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.PWMValue = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.PWMValue.setKeyboardTracking(False)
        self.PWMValue.setDecimals(0)
        self.PWMValue.setMinimum(10.0)
        self.PWMValue.setMaximum(65535.0)
        self.PWMValue.setSingleStep(20.0)
        self.PWMValue.setProperty("value", 5000.0)
        self.PWMValue.setObjectName("PWMValue")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.PWMValue)
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_4)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(180, 20, 160, 80))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_9.setObjectName("label_9")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.PWMRate = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_4)
        self.PWMRate.setKeyboardTracking(False)
        self.PWMRate.setMaximum(65535.0)
        self.PWMRate.setProperty("value", 0.01)
        self.PWMRate.setObjectName("PWMRate")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.PWMRate)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_10.setObjectName("label_10")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.Slope = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_4)
        self.Slope.setKeyboardTracking(False)
        self.Slope.setMaximum(65535.0)
        self.Slope.setProperty("value", 25.0)
        self.Slope.setObjectName("Slope")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Slope)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.Interception = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_4)
        self.Interception.setKeyboardTracking(False)
        self.Interception.setMinimum(-32556.0)
        self.Interception.setMaximum(65535.0)
        self.Interception.setProperty("value", 700.0)
        self.Interception.setObjectName("Interception")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Interception)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "高级设置"))
        self.groupBox.setTitle(_translate("Dialog", "PID设置"))
        self.groupBox_2.setTitle(_translate("Dialog", "PID模式"))
        self.PID_AutoInc.setText(_translate("Dialog", "自动增量"))
        self.PID_ManuInc.setText(_translate("Dialog", "手动增量"))
        self.groupBox_3.setTitle(_translate("Dialog", "PID整定参数"))
        self.label.setText(_translate("Dialog", "Kp"))
        self.label_2.setText(_translate("Dialog", "Ki"))
        self.label_3.setText(_translate("Dialog", "Kd"))
        self.label_4.setText(_translate("Dialog", "Inteval"))
        self.label_5.setText(_translate("Dialog", "SetPoint"))
        self.groupBox_4.setTitle(_translate("Dialog", "调试"))
        self.label_6.setText(_translate("Dialog", "Prescaler"))
        self.label_7.setText(_translate("Dialog", "Smooth"))
        self.label_8.setText(_translate("Dialog", "PWMValue"))
        self.label_9.setText(_translate("Dialog", "PWMRate"))
        self.label_10.setText(_translate("Dialog", "Slope"))
        self.label_11.setText(_translate("Dialog", "InterC"))

