# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIControl.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(510, 282)
        self.BoxCtrl = BoxCtrl(Dialog)
        self.BoxCtrl.setGeometry(QtCore.QRect(13, 10, 120, 80))
        self.BoxCtrl.setObjectName("BoxCtrl")
        self.PWMOpen = QtWidgets.QRadioButton(self.BoxCtrl)
        self.PWMOpen.setGeometry(QtCore.QRect(23, 20, 89, 16))
        self.PWMOpen.setObjectName("PWMOpen")
        self.PWMClose = QtWidgets.QRadioButton(self.BoxCtrl)
        self.PWMClose.setGeometry(QtCore.QRect(23, 40, 89, 16))
        self.PWMClose.setObjectName("PWMClose")
        self.PWMPID = QtWidgets.QRadioButton(self.BoxCtrl)
        self.PWMPID.setGeometry(QtCore.QRect(23, 60, 89, 16))
        self.PWMPID.setObjectName("PWMPID")
        self.BoxMode = BoxMode(Dialog)
        self.BoxMode.setGeometry(QtCore.QRect(13, 100, 120, 101))
        self.BoxMode.setObjectName("BoxMode")
        self.CtrlMode_Dig = QtWidgets.QRadioButton(self.BoxMode)
        self.CtrlMode_Dig.setGeometry(QtCore.QRect(23, 20, 89, 16))
        self.CtrlMode_Dig.setObjectName("CtrlMode_Dig")
        self.CtrlMode_Vot = QtWidgets.QRadioButton(self.BoxMode)
        self.CtrlMode_Vot.setGeometry(QtCore.QRect(23, 40, 89, 16))
        self.CtrlMode_Vot.setObjectName("CtrlMode_Vot")
        self.CtrlMode_Cur = QtWidgets.QRadioButton(self.BoxMode)
        self.CtrlMode_Cur.setGeometry(QtCore.QRect(23, 60, 89, 16))
        self.CtrlMode_Cur.setObjectName("CtrlMode_Cur")
        self.CtrlMode_Der = QtWidgets.QRadioButton(self.BoxMode)
        self.CtrlMode_Der.setGeometry(QtCore.QRect(23, 80, 89, 16))
        self.CtrlMode_Der.setObjectName("CtrlMode_Der")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(143, 17, 361, 181))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.SetPointBar = QtWidgets.QProgressBar(self.groupBox_3)
        self.SetPointBar.setGeometry(QtCore.QRect(13, 0, 20, 161))
        self.SetPointBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SetPointBar.setProperty("value", 24)
        self.SetPointBar.setOrientation(QtCore.Qt.Vertical)
        self.SetPointBar.setObjectName("SetPointBar")
        self.GetPointBar = QtWidgets.QProgressBar(self.groupBox_3)
        self.GetPointBar.setGeometry(QtCore.QRect(43, 0, 20, 161))
        self.GetPointBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.GetPointBar.setProperty("value", 24)
        self.GetPointBar.setOrientation(QtCore.Qt.Vertical)
        self.GetPointBar.setObjectName("GetPointBar")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(13, 160, 16, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(43, 160, 16, 16))
        self.label_2.setObjectName("label_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(73, 10, 141, 51))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(98, 20, 51, 20))
        self.label_3.setObjectName("label_3")
        self.SetPoint = QtWidgets.QLCDNumber(self.groupBox_4)
        self.SetPoint.setGeometry(QtCore.QRect(23, 18, 64, 23))
        self.SetPoint.setObjectName("SetPoint")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_5.setGeometry(QtCore.QRect(73, 80, 141, 51))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(98, 20, 51, 20))
        self.label_4.setObjectName("label_4")
        self.GetPoint = QtWidgets.QLCDNumber(self.groupBox_5)
        self.GetPoint.setGeometry(QtCore.QRect(23, 18, 64, 23))
        self.GetPoint.setObjectName("GetPoint")
        self.BoxUnit = BoxUnit(self.groupBox_3)
        self.BoxUnit.setGeometry(QtCore.QRect(243, 10, 120, 121))
        self.BoxUnit.setObjectName("BoxUnit")
        self.ShowUnit_FS = QtWidgets.QRadioButton(self.BoxUnit)
        self.ShowUnit_FS.setGeometry(QtCore.QRect(23, 20, 89, 16))
        self.ShowUnit_FS.setObjectName("ShowUnit_FS")
        self.ShowUnit_sccm = QtWidgets.QRadioButton(self.BoxUnit)
        self.ShowUnit_sccm.setGeometry(QtCore.QRect(23, 40, 89, 16))
        self.ShowUnit_sccm.setObjectName("ShowUnit_sccm")
        self.ShowUnit_slm = QtWidgets.QRadioButton(self.BoxUnit)
        self.ShowUnit_slm.setGeometry(QtCore.QRect(23, 60, 89, 16))
        self.ShowUnit_slm.setObjectName("ShowUnit_slm")
        self.ShowUnit_V = QtWidgets.QRadioButton(self.BoxUnit)
        self.ShowUnit_V.setGeometry(QtCore.QRect(23, 80, 89, 16))
        self.ShowUnit_V.setObjectName("ShowUnit_V")
        self.ShowUnit_mv = QtWidgets.QRadioButton(self.BoxUnit)
        self.ShowUnit_mv.setGeometry(QtCore.QRect(23, 100, 89, 16))
        self.ShowUnit_mv.setObjectName("ShowUnit_mv")
        self.mplCanvas = MyDynamicMplCanvas(Dialog)
        self.mplCanvas.setGeometry(QtCore.QRect(19, 209, 481, 211))
        self.mplCanvas.setObjectName("mplCanvas")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.BoxCtrl.setTitle(_translate("Dialog", "阀控制"))
        self.PWMOpen.setText(_translate("Dialog", "全开"))
        self.PWMClose.setText(_translate("Dialog", "关闭"))
        self.PWMPID.setText(_translate("Dialog", "常规"))
        self.BoxMode.setTitle(_translate("Dialog", "控制模式"))
        self.CtrlMode_Dig.setText(_translate("Dialog", "数字"))
        self.CtrlMode_Vot.setText(_translate("Dialog", "模拟电压"))
        self.CtrlMode_Cur.setText(_translate("Dialog", "模拟电流"))
        self.CtrlMode_Der.setText(_translate("Dialog", "直接控制"))
        self.label.setText(_translate("Dialog", "SP."))
        self.label_2.setText(_translate("Dialog", "RO."))
        self.groupBox_4.setTitle(_translate("Dialog", "设定点"))
        self.label_3.setText(_translate("Dialog", "% of F.S."))
        self.groupBox_5.setTitle(_translate("Dialog", "瞬时流量"))
        self.label_4.setText(_translate("Dialog", "% of F.S."))
        self.BoxUnit.setTitle(_translate("Dialog", "单位"))
        self.ShowUnit_FS.setText(_translate("Dialog", "% F.S."))
        self.ShowUnit_sccm.setText(_translate("Dialog", "sccm"))
        self.ShowUnit_slm.setText(_translate("Dialog", "slm"))
        self.ShowUnit_V.setText(_translate("Dialog", "V"))
        self.ShowUnit_mv.setText(_translate("Dialog", "mV"))

from UIAction import BoxCtrl, BoxMode, BoxUnit
from mplCanvasWrapper import MyDynamicMplCanvas
